name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: use Go 1.13
        uses: actions/setup-go@v1
        with: 
          go-version: 1.13.x
          
      - name: build game
        run: 
          go get github.com/tmedwards/tweego
          export PATH=$PATH:$(go env GOPATH)/bin
          tweego ld32.tw -o dist/index.html 

      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v2
        env: 
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist